"""Génère les fichiers des stories, les README des epics et l'index (docs/lot0/1-specifications/epics/).

On ne modifie jamais les fichiers générés à la main : on change ce script (listes EPICS, S et STATUS), puis
`backend/.venv/Scripts/python docs/lot0/1-specifications/epics/generer_stories.py` (depuis la racine du dépôt).
"""

import io, os, re, unicodedata

ROOT = os.path.dirname(os.path.abspath(__file__))

EPICS = [
 ("D0", "Socle et mise en service", "Le portail tourne en ligne, sécurisé, sauvegardé, et les RH savent s'en servir.",
  "Sans socle fiable, aucune donnée réelle ne peut entrer (Aucune donnée réelle hors production sécurisée) et la direction ne voit rien fonctionner.", "0, 3"),
 ("D1", "Accès et compte", "Chacun entre dans le portail simplement, et les comptes RH sont fortement protégés.",
  "Un employé sans email doit pouvoir entrer ; les comptes RH voient les dossiers de tous les employés.", "1, 2, 3"),
 ("D2", "Dossier de l'employé", "Chaque employé complète et confirme son dossier lui-même, en quelques minutes.",
  "Besoin 1 : des données fiables. Critère de réussite n°4 : 9 actifs sur 10 au dossier complet.", "1, 4"),
 ("D3", "Certificats", "L'employé fait valoir ses qualifications en déposant ses certificats et suit leur sort.",
  "Besoin 2 : des qualifications prouvées. Sans certificat validé, personne n'apparaît dans les recherches des RH.", "1, 2"),
 ("D4", "Validation RH", "Les RH valident vite, sans conflit d'intérêts, et chaque décision se justifie.",
  "Un certificat ne vaut que validé ; délai cible 5 jours ouvrables (Q2).", "2"),
 ("D5", "Référentiel des unités", "Chaque employé est rattaché à la bonne agence, région et direction.",
  "Sans libellés officiels, les recherches et tableaux de bord par région sont faux (critère n°1).", "1, 4"),
 ("D6", "Pilotage", "La direction et les RH savent qui est qualifié, où, et où en sont les dossiers.",
  "Critère de réussite n°1 : une liste de candidats qualifiés en une minute ; décisions traçables.", "1, 2, 4"),
 ("D7", "Notifications", "L'employé est prévenu au bon moment, par le canal qu'il utilise, sans être harcelé.",
  "Un quart des employés n'ont pas d'email ; WhatsApp touche presque tout le monde (Q7).", "1, 3, 4"),
 ("D8", "Carrière et postes", "L'employé voit les postes ouverts auxquels il est éligible et ce qui lui manque.",
  "Besoin 3 : une raison de participer. Critère n°3 : les employés reviennent d'eux-mêmes.", "4"),
 ("D9", "Demandes et mouvements de carrière", "Les demandes de promotion et de mobilité sont enregistrées, suivies et traitées plus vite.",
  "Critère de réussite n°2 : une demande traitée en quelques jours au lieu de quelques semaines.", "2, 4, lot distinct"),
]

# id, epic, titre, lot, compléments, priorité, EF, RG, décisions, persona, je veux, afin de, [CA], note
S = [
 ("001","D0","Mettre en ligne un socle déployable","0 (démonstrateur)","",
  "Must","ENF-50, ENF-52, ENF-53","—","D-40 (démonstrateur)",
  "développeur","déployer automatiquement depuis GitHub une application dans un conteneur Docker, avec PostgreSQL et un stockage compatible S3, réglée par variables d'environnement",
  "montrer tôt le portail à la direction et passer ensuite sur AWS en changeant la configuration, pas le code",
  ["Un envoi sur la branche de démonstration met l'application en ligne sans action manuelle.",
   "La base est PostgreSQL et les fichiers sont dans un stockage compatible S3, dès le démonstrateur.",
   "Aucune adresse, aucun secret n'est écrit dans le code : tout passe par des variables d'environnement.",
   "Un bandeau « Démonstration · données fictives » figure sur chaque écran hors production.",
   "Seul un jeu de données fictif est chargé ; aucun import de vrai CSV n'est possible hors production.",
   "Hébergement gratuit : site sur Vercel (ou équivalent), API en conteneur sur Render (ou équivalent), base sur Supabase utilisé seulement comme PostgreSQL, fichiers dans un compartiment privé de Supabase Storage, par son interface S3 (liens signés à courte durée) ; aucune fonction propre à ces services (Supabase Auth, accès direct du navigateur à la base, fonctions Vercel, client Supabase dans le navigateur).",
   "Le schéma de la base est créé par des migrations Alembic ; les fichiers passent par un port `FileStorage`.",
   "La même image démarre sur une autre base PostgreSQL en ne changeant que les variables d'environnement (répétition locale sur PostgreSQL 17)."],
  "Voir `../../../9-demonstrateur/plan-demonstrateur.md`, `../../../9-demonstrateur/deploiement-gratuit-et-migration-aws.md` et `../../../9-demonstrateur/mise-en-ligne-pas-a-pas.md`. En ligne depuis le 2026-10-08 : site https://….vercel.app (Vercel), API https://acme-sa.onrender.com (Render), base et fichiers Supabase (us-west-2), déploiement automatique depuis la branche `v2`. Déplacés le 2026-10-08, AWS étant pour plus tard : le dépôt signé, directement dans le stockage, va à US-301 ; la répétition de migration sur le sandbox AWS va à US-002."),
 ("002","D0","Héberger la production en sécurité","3","",
  "Must","EF-308 (antivirus, chiffrement), ENF-01, ENF-02, ENF-04, ENF-07, ENF-20 → ENF-23","—","Questions DIT (architecture AWS)",
  "Administrateur","que le portail tourne sur le compte AWS d'ACME SA, chiffré, sauvegardé et surveillé",
  "ouvrir le portail aux vrais employés sans risque pour leurs données",
  ["HTTPS uniquement, à l'adresse carriere.acmehaiti.com ; la recette est séparée, protégée et sur données fictives.",
   "Base et documents chiffrés ; chaque fichier déposé est analysé par un antivirus avant d'être accessible.",
   "Sauvegarde quotidienne de la base, conservée 30 jours ; documents versionnés.",
   "Une restauration est testée avec succès avant l'ouverture, puis à la fréquence fixée avec la DIT.",
   "Les secrets sont dans AWS Secrets Manager ; une alerte prévient si le coût mensuel dépasse le seuil fixé.",
   "Répétition de migration : la même image Docker que le démonstrateur démarre sur le sandbox AWS (RDS, S3) en ne changeant que les variables d'environnement (venu de US-001)."],
  "Architecture : `../../../6-architecture-aws/architecture-aws.html`."),
 ("003","D0","Former les RH avec un guide d'une page","3","",
  "Must","Demande, livrable 6","—","—",
  "Agent RH","un guide d'une page qui explique mes tâches dans le portail",
  "être autonome dès le lancement, sans formation longue",
  ["Le guide tient sur une page et couvre : se connecter, valider ou rejeter, traiter un signalement, enregistrer une demande.",
   "Une personne RH qui ne connaît pas le portail valide un certificat en recette avec le seul guide."],
  ""),

 ("101","D1","Me connecter sans adresse email","1","",
  "Must","EF-101, EF-102","RG-80","D-30",
  "employé","me connecter avec mon nom, mon prénom, ma date de naissance et mon mot de passe",
  "accéder à mon dossier même sans email (un quart des employés n'en ont pas)",
  ["Étant donné un employé actif de l'export, quand il saisit des informations exactes, alors il arrive sur son accueil.",
   "Après 5 mots de passe erronés, l'espace est suspendu 15 minutes, et le message dit quand réessayer.",
   "Le message d'erreur est le même, que la personne existe ou non : on ne peut pas deviner qui est employé.",
   "Un employé inactif dans l'export ne peut pas se connecter.",
   "Nom, prénom, date de naissance et mot de passe sur un seul écran ; « Première connexion ? Créer mon mot de passe » mène à la création du mot de passe.",
   "Pendant la suspension, un compte à rebours indique le temps restant ; le bouton se réactive à la fin."],
  "Comparaison avec le code actuel et décisions à prendre : `ecarts-accueil-et-connexion.md`."),
 ("102","D1","Choisir ma double authentification","3","",
  "Must","EF-104","RG-81, RG-82","D-41, P-14",
  "Agent RH, Administrateur ou Lecture seule","choisir comment recevoir mon second facteur : code par WhatsApp, code par email, ou application d'authentification (Microsoft Authenticator ou autre application TOTP)",
  "protéger les dossiers de tous les employés sans dépendre d'un seul canal",
  ["À sa première connexion, un compte RH enregistre au moins une méthode avant d'accéder à l'espace RH.",
   "WhatsApp ou email : un code à 6 chiffres, à usage unique, valable quelques minutes (durée à fixer).",
   "Application : la personne scanne un QR code une fois, puis saisit le code à 6 chiffres renouvelé toutes les 30 secondes.",
   "Elle change de méthode depuis son compte, après confirmation avec la méthode actuelle.",
   "Téléphone perdu : un Administrateur réinitialise sa double authentification ; elle en choisit une nouvelle à la connexion suivante.",
   "L'espace RH ne s'ouvre que depuis le réseau des bureaux.",
   "Chaque connexion, réussie ou non, et chaque changement de méthode sont tracés."],
  "Technologie à choisir avec la DIT : Cognito gère l'email et les applications TOTP ; WhatsApp demande un développement en plus. Les employés ont aussi une double authentification : US-106 (D-41). Avancée au démonstrateur (D-42) : écrans, règles et application TOTP faits ; envoi réel des codes WhatsApp et email en attente du service choisi (`MFA_METHODS`)."),
 ("103","D1","Donner un rôle à chaque compte RH","2","",
  "Must","EF-103","RG-41","D-15 → D-19",
  "Administrateur","donner à chaque compte RH un rôle : Administrateur, Agent RH ou Lecture seule",
  "que chacun ne voie et ne fasse que ce qui relève de sa fonction",
  ["Un compte Lecture seule consulte dossiers et tableaux de bord, sans bouton Valider ni Rejeter, et le portail refuse l'action si elle est tentée.",
   "Un employé sans rôle RH n'accède jamais à l'espace RH.",
   "Chaque changement de rôle est tracé (qui, quand, ancien et nouveau rôle)."], ""),
 ("104","D1","Gérer les comptes et débloquer un employé","2","",
  "Must","EF-105","—","—",
  "Administrateur","créer et désactiver les comptes RH, et réinitialiser l'accès d'un employé qui a oublié son mot de passe",
  "qu'aucun employé ne reste bloqué hors de son dossier",
  ["Après réinitialisation, l'employé choisit un nouveau mot de passe à sa prochaine connexion ; ses données sont intactes.",
   "Un compte RH désactivé ne peut plus se connecter ; son historique de décisions reste visible.",
   "Chaque action est tracée."], ""),

 ("105","D1","Découvrir le portail avant de me connecter","1","",
  "Must","Demande 1.1 (accueil, 3 bénéfices) ; Q9 (mascotte)","—","D-08",
  "employé","voir, avant de me connecter, à quoi sert le portail et ce que j'y gagne",
  "avoir envie de compléter mon dossier",
  ["La page d'accueil s'affiche à l'adresse du portail, sans connexion.",
   "Elle présente les 3 bénéfices : promotion, postes vacants, carrière ; avec des icônes et un texte court.",
   "La mascotte « La Penseuse » accueille l'employé (emplacement réservé tant que l'image n'est pas reçue).",
   "Le pourcentage du dossier n'y figure pas : il apparaît après la connexion (D-08).",
   "« Se connecter » mène à l'écran de connexion ; « Une question ? Adressez-vous au service RH de votre agence » est visible.",
   "Aucun chiffre ni lieu non confirmé (nombre d'agences, d'employés)."],
  "Comparaison avec le code actuel : `ecarts-accueil-et-connexion.md`."),
 ("106","D1","Protéger mon accès par une double authentification","3","",
  "Must","EF-104","RG-82, RG-83","D-41, P-14, P-15",
  "employé","confirmer ma connexion avec un code, en plus de mon nom, ma date de naissance et mon mot de passe",
  "que personne d'autre ne puisse ouvrir mon dossier, même en connaissant mes informations",
  ["À sa première connexion, après la création de son mot de passe, l'employé enregistre une méthode avant d'ouvrir son dossier.",
   "Il choisit parmi les méthodes ouvertes : WhatsApp, email ou application d'authentification (mêmes règles de code que US-102) ; un employé sans email n'est jamais bloqué.",
   "À chaque connexion suivante, le code de sa méthode est demandé ; le message d'échec reste unique (US-101).",
   "5 codes faux suspendent l'accès 15 minutes, avec le même compte à rebours que la connexion.",
   "Téléphone perdu : le service RH réinitialise sa double authentification (avec US-104) ; il en choisit une nouvelle à la connexion suivante.",
   "Il change de méthode depuis son compte, après confirmation avec la méthode actuelle.",
   "Chaque connexion et chaque changement de méthode sont tracés, sans jamais écrire le code."],
  "Demande du 2026-10-08 (développeur) : « les employés aussi doivent faire une double authentification » ; elle remplace « employés : non au lancement » (D-41), à faire confirmer par M. Hilaire. ❓ P-15 : méthodes ouvertes aux employés (beaucoup n'ont pas d'email ; WhatsApp a un coût par message à l'échelle de tous les employés) et récupération sans passage à l'agence. Le domaine et les écrans de US-102 se réutilisent."),
 ("201","D2","Voir mon dossier et ma progression","1","",
  "Must","EF-201, EF-206","RG-01, RG-05, RG-17","D-03",
  "employé","voir mes informations RH et « Votre dossier est complet à X % »",
  "savoir en un coup d'œil ce qui me reste à faire",
  ["L'agence, la région et la direction s'affichent avec leur libellé officiel, jamais la valeur brute de l'export.",
   "Le pourcentage = éléments complets ÷ 8, tronqué à l'entier (5 sur 8 = 62 %) ; il change dès qu'une information est enregistrée.",
   "Une agence inconnue du référentiel s'affiche « Unité à confirmer », sans bloquer l'employé."], ""),
 ("202","D2","Compléter mes coordonnées","1","",
  "Must","EF-202, EF-205 (formats), EF-208, EF-209","RG-02, RG-10 → RG-15","D-05, D-06, D-09",
  "employé","saisir ou confirmer mon téléphone, mon adresse, mon email, mon contact d'urgence et mon niveau d'études",
  "que les RH puissent me joindre et connaître mon niveau",
  ["Avant de saisir une nouvelle donnée, il lit la mention d'information (pourquoi, qui y a accès) et donne son consentement, une seule fois.",
   "Un format invalide affiche, près du champ, un message qui dit quoi faire.",
   "« Je n'ai pas d'adresse email » rend le champ email complet.",
   "Le lien du contact d'urgence se choisit dans une liste.",
   "Chaque information enregistrée ou confirmée garde sa date de confirmation."], ""),
 ("203","D2","Confirmer ou signaler mon agence, mon poste, ma date d'embauche","1","",
  "Must (Should pour la cohérence)","EF-203, EF-204, EF-205 (cohérence)","RG-03, RG-16","D-02, D-20",
  "employé","confirmer mon agence, mon poste et ma date d'embauche, ou signaler une erreur, sans pouvoir les modifier",
  "que le système RH soit corrigé à la source",
  ["Ces champs ne sont jamais modifiables par l'employé.",
   "« Ces informations sont exactes » enregistre la date de confirmation.",
   "« Signaler une erreur » demande un motif et enregistre la date, l'ancienne valeur et le motif.",
   "Confirmé ou signalé, le champ compte comme complet.",
   "Une date d'embauche moins de 18 ans après la naissance crée un signalement automatique aux RH, sans bloquer l'employé."], ""),
 ("204","D2","Savoir ce qui me reste avant de déposer","1","",
  "Must","EF-207","RG-06, RG-07","D-01",
  "employé","voir la liste de ce qui manque avant de pouvoir déposer un certificat, avec un lien vers chaque champ",
  "que mon certificat arrive dans un dossier déjà propre",
  ["Tant que le profil n'est pas complet, le dépôt affiche « Il reste N informations à compléter » et un lien vers chacune.",
   "À 8 sur 8, le dépôt s'ouvre sans autre action.",
   "Le profil reste toujours consultable ; aucun message ne ressemble à une sanction."], ""),
 ("206","D2","Retirer l'ancien parcours de mise à jour","1","",
  "Must","—","RG-07","—",
  "employé","n'avoir qu'une seule façon de compléter mon dossier et de déposer mes documents",
  "ne jamais hésiter entre deux parcours",
  ["L'espace employé n'affiche plus l'ancien parcours du MVP : ni la question Oui / Non, ni le brouillon, la vérification et l'envoi, ni « Mes documents ».",
   "Les anciennes adresses (/mise-a-jour/…, /documents) ramènent à « Mon profil ».",
   "Les routes employé de l'ancien parcours (/api/me/update/…, /api/me/documents/…) n'existent plus ; ce qui a déjà été envoyé reste lisible par les RH jusqu'au lot 2."],
  "Demande de l'utilisateur du 2026-10-08 (PRD §7) : US-202 et US-301 remplacent l'ancien parcours."),
 ("207","D2","Aligner l'espace employé sur les écrans validés","1","",
  "Must","—","RG-07, RG-15","D-47",
  "employé","retrouver dans le portail les écrans que la direction a validés",
  "que le portail soit celui qui a été montré et approuvé",
  ["Après la connexion, l'employé arrive sur « Accueil » (écran 06) : bonjour, pourcentage, ce qui reste avec un bouton par élément, état du dépôt ; à la première connexion, « Avant de commencer » (écran 05) passe d'abord.",
   "Chaque écran de l'employé a l'en-tête « Portail Carrière » et la barre du bas Accueil / Mon profil / Mes certificats.",
   "« Mes coordonnées » montre en lecture seule l'identité connue des RH : nom, prénom, matricule, agence et poste (écran 08).",
   "« Mes informations RH », « Déposer un certificat », la confirmation d'envoi et « Mes certificats » reprennent la présentation des écrans 07, 11, 12 et 13 ; le niveau d'études validé s'affiche en tête de « Mes certificats ».",
   "Quand le texte d'un écran contredit une règle du registre (délai, canaux, email obligatoire), la règle l'emporte (D-47)."],
  "Demande de l'utilisateur du 2026-10-09 : les écrans validés par M. Hilaire sont `2-espace-employe-ecrans/` et `3-espace-rh-ecrans/` (D-47). Les écrans RH (menu latéral, A09 « Valeurs à rattacher ») sont repris au début du lot 2."),
 ("205","D2","Confirmer mes informations chaque année","4","",
  "Must","EF-210","RG-60 → RG-64","D-36",
  "employé","confirmer en un clic que mes informations sont toujours exactes",
  "que mon dossier reste à jour sans tout ressaisir",
  ["Une information non confirmée depuis 12 mois est périmée ; un rappel arrive 30 jours avant.",
   "« Ces informations sont-elles toujours exactes ? » : Oui met à jour toutes les dates de confirmation.",
   "Certificats validés et niveau d'études ne se périment jamais."], ""),

 ("301","D3","Déposer un certificat depuis mon téléphone","1","antivirus et stockage chiffré au lot 3, avec US-002",
  "Must","EF-301, EF-302, EF-308","RG-20 → RG-25, RG-31","D-04, D-07",
  "employé au profil complet","déposer un ou plusieurs certificats en photo ou en PDF",
  "que mes qualifications soient reconnues par les RH",
  ["PDF, JPG ou PNG, vérifiés sur le contenu réel du fichier ; 5 Mo au plus, photos réduites avant l'envoi.",
   "Aperçu avant envoi.",
   "Champs obligatoires : type, niveau, intitulé, établissement, année ; pays si étranger ; domaine à partir de Bac + 2.",
   "Année dans le futur refusée ; 20 certificats au plus.",
   "Le fichier est enregistré sous un nom aléatoire.",
   "Le fichier est envoyé par dépôt signé, directement dans le stockage privé, sans passer par l'API (venu de US-001)."], ""),
 ("302","D3","Savoir ce que mon certificat m'apporte","1","",
  "Must (Should pour « ce que ça débloque » et l'avis)","EF-307, EF-607 (avis)","—","D-10",
  "employé","voir, après l'envoi, un remerciement, un récapitulatif, le statut et ce que ce certificat débloque",
  "avoir envie de continuer",
  ["L'écran affiche le récapitulatif et le statut « Reçu ».",
   "Il explique ce que le certificat apporte : niveau validé, apparaître dans les recherches des RH pour les promotions et les postes.",
   "Une question en un clic recueille son avis ; elle peut être ignorée."], ""),
 ("303","D3","Suivre mon certificat","1","« À corriger » et redépôt au lot 2 ; notification avec US-701",
  "Must","EF-303, EF-304, EF-703","RG-26, RG-50","—",
  "employé","voir toujours où en est mon certificat et être prévenu quand il change",
  "ne jamais rester sans réponse",
  ["Statuts : Reçu / En vérification → Validé, ou À corriger.",
   "À corriger (lot 2) : le motif est formulé poliment, et un bouton permet de redéposer ; le redépôt repasse « En vérification ».",
   "Chaque changement de statut déclenche une notification, WhatsApp en priorité."],
  "CA-03 part avec US-701, reportée le 2026-10-08 (prestataire d'envoi non choisi, D-41, livrable 7)."),
 ("304","D3","Garder la preuve des certificats","2","",
  "Must","EF-305","RG-27","—",
  "Agent RH","retrouver tout certificat validé, même remplacé",
  "qu'une qualification prouvée ne se perde jamais",
  ["Un certificat validé ne peut pas être supprimé.",
   "Remplacé, l'ancien reste archivé avec son historique de décisions."], ""),
 ("305","D3","Un niveau d'études prouvé","2","",
  "Should","EF-306","RG-18, RG-30","—",
  "Agent RH","voir le niveau d'études calculé sur le plus haut certificat validé",
  "comparer les employés sur des preuves",
  ["Le niveau du profil = rang le plus élevé parmi les certificats validés ; à défaut, le niveau déclaré.",
   "Un niveau déclaré supérieur au niveau validé est signalé aux RH."], ""),

 ("401","D4","Prendre le dossier suivant","2","",
  "Must (Should pour la réaffectation)","EF-401, EF-405, EF-406","RG-40, RG-42, RG-43","D-12, D-14",
  "Agent RH","prendre le certificat suivant dans une file commune",
  "qu'aucun dossier ne reste bloqué quand une collègue est absente",
  ["La file est commune et triée du plus ancien au plus récent ; au-delà de 5 jours ouvrables, le dossier est en alerte.",
   "Un dossier pris passe « en cours » à mon nom ; personne d'autre ne peut le traiter en même temps.",
   "Mon propre certificat n'apparaît jamais dans ma file.",
   "Un Administrateur peut réaffecter un dossier à un autre valideur."], ""),
 ("402","D4","Examiner et décider","2","",
  "Must","EF-402, EF-403, EF-404, EF-407","RG-44, RG-45, RG-46","D-13",
  "Agent RH","voir le document à gauche et le profil à droite, puis valider ou rejeter",
  "décider vite et de façon justifiable",
  ["Rejeter demande un des 10 motifs ; le commentaire est obligatoire pour « Autre ».",
   "Je peux corriger le niveau, l'intitulé, l'établissement, l'année et le domaine ; chaque correction est tracée.",
   "Chaque décision enregistre valideur, date, heure, décision et motif ; l'historique du dossier les montre.",
   "L'employé est notifié de la décision."], ""),
 ("403","D4","Traiter les signalements","2","",
  "Must","EF-408","RG-03, RG-16","D-20",
  "Agent RH","traiter dans une file les erreurs signalées par les employés",
  "que le système RH soit corrigé et le dossier assaini",
  ["Chaque signalement montre le champ, l'ancienne valeur, le motif et la date.",
   "Je le clôture avec une suite donnée ; l'employé en est informé.",
   "Les signalements automatiques (dates incohérentes) arrivent dans la même file."], ""),

 ("501","D5","Tenir le référentiel officiel","1","interface de gestion au lot 4",
  "Must (Should pour l'interface)","EF-501, EF-502, EF-503, EF-505","RG-70, RG-71","D-26, D-27",
  "responsable du référentiel","tenir la liste officielle des agences, régions et directions, et son lien avec l'export RH",
  "que chaque employé soit rattaché à la bonne unité et que les tableaux de bord soient justes",
  ["Au lot 1, le référentiel est un fichier Excel importé par un Administrateur ; l'import refuse un fichier incohérent (code en double, agence sans région).",
   "Chaque unité a un code stable qui ne change jamais ; un renommage garde l'ancien libellé.",
   "Une agence a une seule région à la fois, avec dates de début et de fin."],
  "Fait au lot 1 (2026-10-08) : import d'un classeur Excel à deux onglets (« Unités », « Correspondances ») depuis l'écran RH « Référentiel ». Le critère « au lot 4, une interface remplace le fichier » est passé à US-503."),
 ("503","D5","Gérer le référentiel à l'écran","4","",
  "Should","EF-505","RG-70, RG-71","D-27",
  "responsable du référentiel","créer, renommer et rattacher les unités directement dans le portail",
  "ne plus passer par un fichier Excel et un Administrateur pour chaque changement",
  ["Au lot 4, une interface remplace le fichier : la responsable, son assistante et les Administrateurs modifient le référentiel à l'écran (EF-505).",
   "Les règles de l'import restent vraies : code stable, ancien libellé gardé au renommage, une seule région à la fois avec dates.",
   "Chaque modification est tracée."],
  "Venue de US-501 (critère CA-04), le 2026-10-08."),
 ("502","D5","Rattacher les valeurs inconnues","1","",
  "Must","EF-504","RG-17","—",
  "Administrateur","voir les valeurs de l'export qui n'ont pas de correspondance",
  "qu'aucune ne soit ignorée",
  ["Une valeur inconnue va dans la liste « À rattacher », avec le nombre d'employés concernés.",
   "Ces employés sont « Unité à confirmer », sans être bloqués.",
   "Une fois rattachée, la valeur disparaît de la liste et les employés prennent le libellé officiel."], ""),

 ("601","D6","Voir l'état des dossiers d'un coup d'œil","2","",
  "Must","EF-601","RG-06","D-17, D-22",
  "Administrateur ou Lecture seule","voir un tableau de bord",
  "savoir où en est l'institution et où relancer",
  ["Nombre d'employés, % de dossiers complets, certificats reçus, en attente et rejetés.",
   "Répartition par agence, région et direction, avec les libellés officiels.",
   "Les chiffres correspondent à ceux de la liste filtrée (US-602)."], ""),
 ("602","D6","Trouver les employés qualifiés en une minute","2","",
  "Must","EF-602, EF-603","RG-30, RG-31","D-22",
  "Agent RH","chercher les employés par niveau validé, domaine et unité",
  "proposer des candidats pour une promotion ou un poste (critère de réussite n°1)",
  ["« Au moins Licence » + « Comptabilité » + « Région Sud » donne la liste en quelques secondes.",
   "Seuls les certificats validés comptent.",
   "La liste se filtre aussi par agence, statut du dossier et niveau d'études.",
   "Chaque consultation d'un dossier depuis la liste est tracée."], ""),
 ("603","D6","Exporter une liste","2","",
  "Should","EF-604","—","D-18",
  "Administrateur","exporter la liste filtrée en Excel ou CSV",
  "la travailler hors du portail",
  ["L'export reprend exactement les filtres affichés.",
   "Il ne contient jamais le contact d'urgence ; chaque export est tracé (qui, quand, quels filtres)."], ""),
 ("604","D6","Rendre compte de chaque action","2","",
  "Must","EF-605, ENF-08","RG-45","D-19",
  "Administrateur","consulter le journal d'audit",
  "justifier toute décision et toute consultation",
  ["Le journal montre qui a modifié quoi et quand, et qui a consulté quel document.",
   "Personne ne peut modifier ni supprimer une ligne du journal.",
   "Il se filtre par personne, employé et période."], ""),
 ("605","D6","Mesurer si les employés reviennent","1","",
  "Must (Should pour l'avis)","EF-607","—","—",
  "Administrateur","savoir combien d'employés se connectent d'eux-mêmes et ce qu'ils pensent du dépôt",
  "mesurer les critères de réussite n°3 et « plaisir »",
  ["Chaque connexion d'un employé est enregistrée avec sa date.",
   "Les réponses à la question en un clic sont comptées, sans commentaire libre."], ""),
 ("606","D6","Changer une règle sans développeur","4","",
  "Should","EF-606, ENF-51","Toutes","—",
  "Administrateur","modifier les règles et les listes (champs obligatoires, niveaux, motifs) sans toucher au code",
  "que le portail suive l'évolution de l'institution",
  ["Une règle modifiée s'applique dès l'enregistrement.",
   "Chaque modification est tracée avec l'ancienne et la nouvelle valeur."], ""),

 ("701","D7","Être prévenu par le bon canal","1","",
  "Must (Should pour l'ordre des canaux)","EF-701, EF-702, EF-703","RG-50","—",
  "employé","choisir d'être prévenu par WhatsApp et consentir aux messages",
  "suivre mes démarches sans ouvrir le portail tous les jours",
  ["Le consentement WhatsApp se donne et se retire dans le profil.",
   "Ordre des canaux : WhatsApp, puis email institutionnel, puis email personnel avec consentement.",
   "WhatsApp passe uniquement par l'API officielle de Meta, avec des modèles approuvés."],
  "Prestataire et budget WhatsApp : livrable 7. **Reportée le 2026-10-08** par l'utilisateur : le prestataire d'envoi n'est pas choisi (D-41)."),
 ("702","D7","Être relancé sans être harcelé","1","",
  "Should","EF-704","RG-51, RG-52, RG-53","D-21, D-34, D-35",
  "employé au dossier incomplet","recevoir quelques rappels positifs",
  "terminer mon dossier sans me sentir sanctionné",
  ["Rappels entre 1 et 7 jours puis à 14 jours, au plus 3.",
   "Envoyés du lundi au vendredi, de 8 h à 18 h.",
   "Plus aucun rappel dès que le dossier est complet."],
  "**Reportée le 2026-10-08** avec US-701 ; le déclenchement des rappels (commande planifiée ou tâche de l'API) reste à décider."),
 ("703","D7","Annoncer le portail et les postes ouverts","3","résumé des postes au lot 4",
  "Must (Should pour le résumé)","EF-705, EF-706","—","—",
  "Administrateur","envoyer le message de lancement, puis un résumé périodique des postes ouverts",
  "que les employés sachent pourquoi revenir",
  ["Le message de lancement explique les 3 bénéfices et donne le lien.",
   "Le résumé (lot 4) ne liste que les postes publiés et non confidentiels."], ""),

 ("801","D8","Voir les postes auxquels je suis éligible","4","",
  "Must","EF-801, EF-805, EF-806","RG-72","D-24",
  "employé","voir dans « Ma carrière » les postes ouverts et si j'y suis éligible",
  "savoir ce qui me manque pour progresser",
  ["Chaque poste porte un indicateur vert (éligible) ou orange (pas encore), avec un texte, pas seulement une couleur.",
   "Orange : le portail dit ce qui manque (« Il vous manque un certificat de niveau Licence validé »).",
   "Seules les données validées comptent ; l'indicateur informe et ne décide jamais.",
   "Je peux toujours manifester mon intérêt ; s'il est orange, il est marqué « hors critères »."], ""),
 ("802","D8","Publier un poste","4","",
  "Must (Should pour la confidentialité)","EF-803, EF-804, EF-807","—","—",
  "Agent RH","saisir un poste ouvert, que l'Administrateur publie après l'avoir validé",
  "que les postes soient pourvus en priorité en interne",
  ["Fiche : intitulé et code, unité, grade visé, mission, critères, dates d'ouverture et limite.",
   "Statuts Brouillon, Publié, Clôturé, Pourvu, avec date et auteur ; un critère modifié après publication est tracé.",
   "Un Administrateur peut marquer un poste confidentiel, avec un motif ; seules les personnes ciblées le voient."], ""),
 ("803","D8","Ajouter mes formations et expériences","4","",
  "Should","EF-802","RG-04","—",
  "employé","ajouter mes formations, expériences et compétences",
  "compléter mon profil de carrière",
  ["Ces ajouts ne changent jamais le verrou ni le pourcentage."], ""),

 ("901","D9","Enregistrer une demande reçue par lettre","2","",
  "Must","EF-901 (lettre), EF-902, EF-903","RG-74","D-33",
  "Agent RH","enregistrer à réception une demande de promotion ou de mobilité reçue par lettre",
  "mesurer et réduire le délai de traitement (critère de réussite n°2)",
  ["Fiche : employé, date de réception, canal, type, poste visé, motivation, lettre scannée, étape, responsable.",
   "La demande suit 7 étapes, de la réception à la clôture (acceptée, refusée, reportée ou retirée) ; chaque passage est daté.",
   "Aucune demande ne peut être supprimée.",
   "Le profil de l'employé au moment de la demande est conservé."], ""),
 ("902","D9","Déposer et suivre ma demande en ligne","4","",
  "Must","EF-901 (portail), EF-904","RG-73, RG-74","D-23, D-37",
  "employé","déposer une demande de promotion ou de mobilité, même sans poste ouvert, et la suivre",
  "ne plus attendre sans nouvelles",
  ["Un accusé de réception arrive sous 2 jours ouvrables.",
   "« Mes demandes » montre l'étape en cours de chacune."], ""),
 ("903","D9","Contrôler les mouvements lus dans les lettres","2","ancienneté dans le poste au lot 4",
  "Should (Must pour l'ancienneté)","EF-906, EF-907","RG-72","D-33, D-38",
  "Agent RH","contrôler les promotions, transferts et nominations que le portail a lus dans les lettres scannées",
  "connaître l'ancienneté de chacun dans son poste",
  ["Je vois la lettre d'un côté, les champs lus de l'autre ; rien n'est enregistré sans ma validation.",
   "Les salaires et montants ne sont jamais extraits ni stockés.",
   "Ancienneté dans le poste = aujourd'hui moins la date d'effet du dernier mouvement, ou la date d'embauche."],
  "Test préalable sur 20 à 30 lettres (livrable 5)."),
 ("904","D9","Reprendre l'historique des demandes","2","",
  "Should","EF-905","—","—",
  "Agent RH","importer l'historique des demandes depuis un fichier Excel",
  "que le registre parte avec le passé",
  ["L'import refuse une ligne incomplète et dit pourquoi, sans bloquer les autres.",
   "Les demandes importées sont marquées comme telles."], ""),
 ("905","D9","Produire les lettres de promotion","Lot distinct","",
  "Could (à préciser)","Q5 §6, étape B","—","—",
  "Agent RH","produire depuis le portail la lettre d'une promotion, d'un transfert ou d'une nomination décidée",
  "ne plus ressaisir les lettres et que chaque mouvement soit enregistré dès sa création",
  ["La lettre reprend les données validées du mouvement, sans aucun montant de salaire.",
   "Le mouvement est enregistré au moment où la lettre est produite."],
  "Lot distinct, après le lot 4 : périmètre à préciser avec M. Hilaire."),
 ("906","D9","Renvoyer les mouvements au système RH","Lot distinct","",
  "Could (à préciser)","Q5 §6, étape B ; QR-03","—","D-20",
  "Administrateur","exporter les mouvements et corrections validés vers le système RH",
  "que le système RH et le portail disent la même chose",
  ["L'export ne contient que des données validées, dans un format convenu avec la DIT.",
   "Chaque export est tracé."],
  "Lot distinct : format et fréquence à convenir avec la DIT."),
]

STATUS = {"105": "Fait", "101": "Fait", "001": "Fait", "102": "En cours", "501": "Fait", "201": "Fait", "202": "Fait", "203": "Fait", "204": "Fait", "206": "Fait", "301": "Fait", "302": "Fait", "303": "Fait", "502": "Fait", "605": "Fait", "207": "Fait"}

LOT_ORDER = {"0 (démonstrateur)": 0, "1": 1, "2": 2, "3": 3, "4": 4, "Lot distinct": 5}

def slug(t):
    t = unicodedata.normalize("NFKD", t).encode("ascii", "ignore").decode()
    t = re.sub(r"[^a-zA-Z0-9]+", "-", t.lower()).strip("-")
    return t[:60].rstrip("-")

# Un dossier par lot (choix du 2026-10-08) : clé du lot, dossier, titre, but, démonstration de fin
LOTS = [
 ("0 (démonstrateur)", "demonstrateur", "Démonstrateur", "Montrer tôt à la direction générale ce qui se construit, sur données fictives", "Parcours de 5 minutes, en ligne (plan du démonstrateur)"),
 ("1", "lot-1-parcours-certificat", "Lot 1 — Parcours « certificat »", "Un employé complète son profil et dépose ses certificats", "Un employé au dossier complet et un au dossier incomplet, en recette"),
 ("2", "lot-2-traitement-rh", "Lot 2 — Traitement RH", "Les RH valident, pilotent et enregistrent les demandes", "File de validation et tableau de bord sur données fictives"),
 ("3", "lot-3-mise-en-service", "Lot 3 — Mise en service", "Le portail est hébergé, sécurisé et annoncé", "Test complet en recette ; guide RH ; message de lancement ; ouverture aux employés"),
 ("4", "lot-4-carriere-et-engagement", "Lot 4 — Carrière et engagement", "L'employé voit ses postes éligibles et suit ses demandes", "Un employé avec un champ périmé ; un poste publié avec indicateurs vert et orange"),
 ("Lot distinct", "lot-distinct-lettres-et-systeme-rh", "Lot distinct — Lettres et retour au système RH", "Le portail produit les lettres et renvoie les mouvements", "À préciser"),
]
LOT_DIR = {key: folder for key, folder, *_ in LOTS}

def article(p):
    return "qu'" if p[0].lower() in "aeiouéèêh" else "que "

os.makedirs(ROOT, exist_ok=True)
paths = {}
for (sid, ep, titre, lot, compl, prio, ef, rg, dec, persona, veux, afin, cas, note) in S:
    e = next(x for x in EPICS if x[0] == ep)
    d = os.path.join(ROOT, LOT_DIR[lot])
    os.makedirs(d, exist_ok=True)
    fn = f"US-{sid}-{slug(titre)}.md"
    paths[sid] = f"{LOT_DIR[lot]}/{fn}"
    lot_txt = lot if not compl else f"{lot} ({compl})"
    afin_word = "afin d'" if afin[0].lower() in "aeiouéèêh" and not afin.startswith("que") and not afin.startswith("qu") else ("afin " if afin.startswith(("que", "qu'")) else "afin de ")
    lines = [f"# US-{sid} — {titre}", "", "| | |", "|---|---|",
             f"| **Statut** | {STATUS.get(sid, 'Pas encore')} |",
             f"| **Epic** | {ep} {e[1]} |",
             f"| **Lot** | {lot_txt} |",
             f"| **Priorité** | {prio} |",
             f"| **Exigences** | {ef} |",
             f"| **Règles** | {rg} |",
             f"| **Décisions liées** | {dec} |", "",
             "## Récit", "",
             f"> En tant {article(persona)}**{persona}**, je veux {veux}, **{afin_word}{afin}**.", "",
             "## Pourquoi", "", e[3], "",
             "## Critères d'acceptation", ""]
    for i, c in enumerate(cas, 1):
        lines.append(f"- **CA-{i:02d}** {c}")
    if note:
        lines += ["", "## Notes", "", note]
    box = "[x]" if STATUS.get(sid) == "Fait" else "[ ]"
    lines += ["", "## Definition of Done", "",
              f"- {box} Chaque critère d'acceptation est couvert par un test vert",
              f"- {box} Écran vérifié sur téléphone (390 px) et sur ordinateur (1280 px), s'il y a un écran",
              f"- {box} Données fictives uniquement ; aucun salaire, aucune colonne exclue dans l'API ni les journaux",
              f"- {box} Statut mis à jour ici et dans `../README.md`", ""]
    io.open(os.path.join(d, fn), "w", encoding="utf-8").write("\n".join(lines))

# README de chaque lot : ses stories, groupées par epic
for key, folder, title, goal, demo in LOTS:
    rows = [x for x in S if x[3] == key]
    L = [f"# {title}", "", f"**But :** {goal}.", "", f"**Démonstration de fin :** {demo}.", "",
         f"{len(rows)} stories, groupées par epic. Statuts et enchaînements : [index](../README.md).", ""]
    for code, name, goal_e, why, lots in EPICS:
        group = sorted([x for x in rows if x[1] == code], key=lambda x: x[0])
        if not group: continue
        L += [f"## {code} {name}", "", goal_e, "",
              "| Story | Titre | Priorité | Complément plus tard | Statut |", "|---|---|---|---|---|"]
        for x in group:
            L.append(f"| [US-{x[0]}]({os.path.basename(paths[x[0]])}) | {x[2]} | {x[5]} | {x[4] or '—'} | {STATUS.get(x[0], 'Pas encore')} |")
        L.append("")
    io.open(os.path.join(ROOT, folder, "README.md"), "w", encoding="utf-8").write("\n".join(L))

# Index + plan par lots
I = ["# Epics et user stories de la refonte", "",
     "| | |", "|---|---|",
     "| **Version** | 0.1, 2026-10-07 — première rédaction, à relire avec les maquettes puis à valider par M. Hilaire |",
     "| **Source** | `../cahier-des-charges.md` (exigences EF, ENF), `../tableau-unique-des-regles.md` (RG), `../decisions-a-valider.md` (D) |",
     "| **Numérotation** | Une story porte le numéro de son epic, comme les exigences : US-301 = 1re story de l'epic D3 (EF-301…). Elle est **indépendante** des US-01 → US-35 du MVP et de la V2, retirées de la branche `v2` le 2026-10-08 (historique git, branche `main`) |", "| **Statuts** | Cet index est la source de vérité des statuts ; le fichier de chaque story et `agent.md` §0 les reprennent |", "",
     f"{len(EPICS)} epics, {len(S)} user stories. Chaque fichier de story contient le récit, le pourquoi, les critères d'acceptation et la Definition of Done.", "",
     "## Plan par lots", "",
     "Une story appartient au lot où elle est livrée ; quand un complément arrive plus tard, il est indiqué entre parenthèses.", ""]
for key, folder, title, goal, demo in LOTS:
    rows = sorted([s for s in S if s[3] == key], key=lambda s: s[0])
    if not rows: continue
    I += [f"### [{title}]({folder}/README.md)", "", f"**But :** {goal}. **Démonstration de fin :** {demo}.", "",
          "| Story | Epic | Titre | Priorité | Complément plus tard | Statut |", "|---|---|---|---|---|---|"]
    for s in rows:
        I.append(f"| [US-{s[0]}]({paths[s[0]]}) | {s[1]} | {s[2]} | {s[5]} | {s[4] or '—'} | {STATUS.get(s[0], 'Pas encore')} |")
    I.append("")
I += ["### Enchaînements à respecter", "",
      "| Avant | Après | Pourquoi |", "|---|---|---|",
      "| Référentiel validé (US-501) | Lot 1 en recette | L'employé voit les libellés officiels |",
      "| Dépôt (US-301) | Validation (US-401, US-402) | Rien à valider sans dépôt |",
      "| Certificats validés, mouvements contrôlés (lot 2) | Éligibilité (US-801) | L'éligibilité ne compte que les données validées |",
      "| Hébergement sécurisé (US-002) | Données réelles, ouverture aux employés | Aucune donnée réelle hors production sécurisée |",
      "| Socle déployable (US-001) | Démonstrateur, puis chaque lot en recette | Chaque story se montre en ligne dès qu'elle est finie |", "",
      "### Le démonstrateur pioche dans plusieurs lots", "",
      "Parcours du démonstrateur (`../../9-demonstrateur/plan-demonstrateur.md`) : US-001 → US-101, US-201, US-202, US-301 (lot 1) → US-401, US-402 (lot 2) → US-601 (lot 2) → US-901 (lot 2) → US-801 (lot 4). Une story montrée au démonstrateur garde son statut « Pas encore » tant que sa Definition of Done n'est pas cochée.", "",
      "## Epics", "", "Un epic regroupe les stories d'un même bloc fonctionnel, souvent sur plusieurs lots ; chaque story indique son epic dans son en-tête.", "",
      "| Epic | Objectif | Pourquoi | Stories |", "|---|---|---|---|"]
for (code, name, goal, why, lots) in EPICS:
    ids = ", ".join(f"[US-{s[0]}]({paths[s[0]]})" for s in sorted([s for s in S if s[1] == code], key=lambda s: s[0]))
    I.append(f"| {code} {name} | {goal} | {why} | {ids} |")
I += ["", "## Statuts", "", "| Statut | Signification |", "|---|---|",
      "| **Pas encore** | Aucun code écrit |", "| **En cours** | Commencée |",
      "| **Fait** | Tous les critères d'acceptation couverts par des tests verts, Definition of Done cochée |", ""]
io.open(os.path.join(ROOT, "README.md"), "w", encoding="utf-8").write("\n".join(I))
print(len(EPICS), "epics", len(S), "stories")
for key, folder, *_ in LOTS:
    print(folder, [s[0] for s in S if s[3] == key])
