"""journal des connexions

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-08 23:48:39.914412
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.infrastructure.database

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_login_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_login_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_login_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_login_at'))

    op.drop_table('employee_login')
    # ### end Alembic commands ###
