"""dossier de l'employe

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 20:17:26.154735
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.infrastructure.database

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('given', sa.Boolean(), nullable=False),
    sa.Column('at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('text_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_employee_id'), ['employee_id'], unique=False)

    op.create_table('dossier',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('no_email', sa.Boolean(), nullable=False),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('dossier_confirmation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('information', sa.String(), nullable=False),
    sa.Column('gesture', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dossier_confirmation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossier_confirmation_employee_id'), ['employee_id'], unique=False)

    op.create_table('emergency_contact',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['dossier.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_contact')
    with op.batch_alter_table('dossier_confirmation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossier_confirmation_employee_id'))

    op.drop_table('dossier_confirmation')
    op.drop_table('dossier')
    with op.batch_alter_table('consent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_employee_id'))

    op.drop_table('consent')
    # ### end Alembic commands ###
