"""double authentification des comptes RH

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 09:40:23.403323
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.infrastructure.database

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mfa_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mfa_destination', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mfa_pending_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mfa_pending_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mfa_pending_destination', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mfa_code_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mfa_code_expires_at', app.shared.infrastructure.database.UtcDateTime(), nullable=True))
        batch_op.add_column(sa.Column('mfa_change_allowed_until', app.shared.infrastructure.database.UtcDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.drop_column('mfa_change_allowed_until')
        batch_op.drop_column('mfa_code_expires_at')
        batch_op.drop_column('mfa_code_hash')
        batch_op.drop_column('mfa_pending_destination')
        batch_op.drop_column('mfa_pending_secret')
        batch_op.drop_column('mfa_pending_method')
        batch_op.drop_column('mfa_destination')
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('mfa_method')

    # ### end Alembic commands ###
