"""signalements d'erreur

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 21:11:31.715642
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.infrastructure.database

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('information', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('current_value', sa.String(), nullable=False),
    sa.Column('indicated_value', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_report_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_report_employee_id'))

    op.drop_table('error_report')
    # ### end Alembic commands ###
