"""certificats

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-08 23:43:16.473755
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.infrastructure.database

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('certificate_type', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('domain_other', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_employee_id'), ['employee_id'], unique=False)

    op.create_table('certificate_feedback',
    sa.Column('certificate_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('certificate_id')
    )
    with op.batch_alter_table('certificate_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_feedback_employee_id'), ['employee_id'], unique=False)

    op.create_table('certificate_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('certificate_id', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('certificate_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_file_certificate_id'), ['certificate_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_file_certificate_id'))

    op.drop_table('certificate_file')
    with op.batch_alter_table('certificate_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_feedback_employee_id'))

    op.drop_table('certificate_feedback')
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_employee_id'))

    op.drop_table('certificate')
    # ### end Alembic commands ###
