"""schema initial du portail

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 09:01:18.317495
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.infrastructure.database

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('username_key', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.shared.infrastructure.database.UtcDateTime(), nullable=True),
    sa.Column('created_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('last_login_at', app.shared.infrastructure.database.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username_key')
    )
    op.create_table('career_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('qualification_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_month', sa.Date(), nullable=True),
    sa.Column('end_month', sa.Date(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('skill_level', sa.String(), nullable=True),
    sa.Column('created_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('proof_original_name', sa.String(), nullable=True),
    sa.Column('proof_stored_name', sa.String(), nullable=True),
    sa.Column('proof_content_type', sa.String(), nullable=True),
    sa.Column('proof_size_bytes', sa.Integer(), nullable=True),
    sa.Column('proof_uploaded_at', app.shared.infrastructure.database.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_entry_employee_id'), ['employee_id'], unique=False)

    op.create_table('career_profile',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('last_changed_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_employee_id'), ['employee_id'], unique=False)

    op.create_table('employee_account',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.shared.infrastructure.database.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('employee_update',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('submitted_at', app.shared.infrastructure.database.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('session',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('created_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('last_seen_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('expires_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_subject_id'), ['subject_id'], unique=False)

    op.create_table('employee_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=False),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('changed_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['update_id'], ['employee_update.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('update_id', 'field_name')
    )
    op.create_table('employee_submitted_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=False),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('changed_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['update_id'], ['employee_update.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('update_id', 'field_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_submitted_change')
    op.drop_table('employee_change')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_subject_id'))

    op.drop_table('session')
    op.drop_table('employee_update')
    op.drop_table('employee_account')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_employee_id'))

    op.drop_table('document')
    op.drop_table('career_profile')
    with op.batch_alter_table('career_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_entry_employee_id'))

    op.drop_table('career_entry')
    op.drop_table('admin_account')
    # ### end Alembic commands ###
