"""roles des comptes rh et tracabilite des modifications

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-09 12:10:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.infrastructure.database

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False, server_default='ADMIN'))

    op.create_table('admin_role_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('old_role', sa.String(), nullable=False),
    sa.Column('new_role', sa.String(), nullable=False),
    sa.Column('at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_role_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_role_change_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_role_change_at'), ['at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_role_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_role_change_at'))
        batch_op.drop_index(batch_op.f('ix_admin_role_change_admin_id'))

    op.drop_table('admin_role_change')
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.drop_column('role')
    # ### end Alembic commands ###
