"""referentiel des unites

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 16:07:08.780925
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.shared.infrastructure.database

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('export_mapping',
    sa.Column('export_column', sa.String(), nullable=False),
    sa.Column('export_value', sa.String(), nullable=False),
    sa.Column('unit_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['unit_code'], ['unit.code'], ),
    sa.PrimaryKeyConstraint('export_column', 'export_value')
    )
    op.create_table('unit_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_code', sa.String(), nullable=False),
    sa.Column('parent_code', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('imported_at', app.shared.infrastructure.database.UtcDateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_code'], ['unit.code'], ),
    sa.ForeignKeyConstraint(['unit_code'], ['unit.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_attachment_unit_code'), ['unit_code'], unique=False)

    op.create_table('unit_former_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['unit_code'], ['unit.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_former_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_former_label_unit_code'), ['unit_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_former_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_former_label_unit_code'))

    op.drop_table('unit_former_label')
    with op.batch_alter_table('unit_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_attachment_unit_code'))

    op.drop_table('unit_attachment')
    op.drop_table('export_mapping')
    op.drop_table('unit')
    # ### end Alembic commands ###
