from typing import Protocol

from app.auth.domain.model import Account, Session, SubjectType


class AccountRepository(Protocol):
    def get(self, employee_id: str) -> Account | None: ...

    def save(self, account: Account) -> None: ...


class SessionRepository(Protocol):
    def get(self, token_hash: str) -> Session | None: ...

    def save(self, session: Session) -> None: ...

    def delete(self, token_hash: str) -> None: ...

    def delete_for_subject(self, subject_type: SubjectType, subject_id: str) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...

    def verify(self, password_hash: str, password: str) -> bool: ...
